build:
  version: "1.0"

accounts:
  message: "Welcome to AbbeyBank accounts related prod APIs "
  contactDetails:
    name: "Moyinoluwa - Product Owner"
    email: "moyit@Abbeybank.com"
  onCallSupport:
    - 08046636111
    - +440754519226