build:
  version: "3.0"

accounts:
  message: "Welcome to AbbeyBank accounts related local APIs "
  contactDetails:
    name: "Oga Oddy - Developer"
    email: "smitha@Abbeybank.com"
  onCallSupport:
    - 08036636560
    - +4407401199310





